### ISSUE TITLE
Semicolon and other style conventions.

### ISSUE THREAD

**Issue by bearbin** [cuberite/Core#11]
I assume that this repo should be using tabs for indentation and spaces for alignment, and unix line endings. Should we be using semicolons at the end of lines (they're optional) as they seem to have mixed use in the repo. Also, if there are any other lua conventions that must be followed, please tell me :smile:

**Comment by madmaxoft** [comment]
I'm eating my own words from four years ago. There's no need for semicolons in Lua, so let's let them go :)
