### ISSUE TITLE
core.back permission doesn't work

### ISSUE THREAD

**Issue by mathias-github** [cuberite/Core#119]
There seems to be a problem with the core.back permission. I've added it to the "Default" group, but it still returns a "Forbidden command; insufficient privileges: "/back"" message in-game.

**Comment by madmaxoft** [comment]
This should have worked.

When the player is connected, have a look in the webadmin, in the Core -> Players tab and click View details next to that user; check if the permission is listed there.

We need a better permission editor and a way to audit permissions effectively. There's no way to check permissions for a player that is not connected and the current editor makes it quite difficult to do the check manually.

**Comment by mathias-gh** [comment]
I added myself to the "Default" group. "core.back" is listed in the permissions list for my player, but the command still returns the same "Forbidden command" error.

**Comment by mathias-gh** [comment]
Issue was solved after removing and re-adding the core.back permission.
