### ISSUE TITLE
Can't remove groups from WebAdmin

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/Core#140]
Reported by @Shadowraix in mc-server/MCServer#2083:

If you try to remove a group within the ranks tab under 'edit groups' in WebAdmin it returns this error.

"An internal error has occurred, no handler for subpage removegroup."

**Comment by HelenaKitty** [comment]
I have mentioned this problem to @sphinxc0re on his forum thread `libcuberite`, You can find the thread at https://forum.cuberite.org/thread-2740.html

I really do believe this is a major, but simple issue when it comes down to administering Cuberite server.
