### ISSUE TITLE
Time of day overflow after calling '/time day'

### ISSUE THREAD

**Issue by Woazboat** [cuberite/Core#164]
Calling "/time day" somehow caused the time of day to overflow. The sun/moon was wildly spinning around and further calls to "/time day" increased the animation speed.
Was fixed through a server restart and is non-reproducible.

Cuberite server and core plugin from commit 3c272b55ea1239238ad9726bba9f7dc8b130e545

https://imgur.com/lkNfl1d

**Comment by madmaxoft** [comment]
I suspect this could be the result of a race condition related to the time animations. Two players asking for different times almost-simultaneously would probably cause problems.

**Comment by bearbin** [comment]
Fixed by #229
