### ISSUE TITLE
/spawn command doesn't work

### ISSUE THREAD

**Issue by mathiascode** [cuberite/Core#169]
The /spawn command currently doesn't work. The problem lies in ChunkStay, but I don't know what the best way would be to fix this issue.

You can reproduce the issue by downloading the latest binaries on the homepage, and executing /spawn in-game.

**Comment by ElNounch** [comment]
nil value for onChunkAvailable is what trigger the problems.
As a work-around, at https://github.com/cuberite/Core/blob/master/spawn.lua#L10
```lua
local OnChunkAvailable = function(ChunkX, ChunkZ)
end
```
Seems to be variadic template magic of GetStackValues (in relation with https://github.com/cuberite/cuberite/commit/bf88312a1664311968736b4ba7ce1458c8b0954e may be ?).
Manually splitting into two individuals GetStackValue calls fix /spawn (https://github.com/cuberite/cuberite/blob/master/src/Bindings/ManualBindings_World.cpp#L107 ).

**Comment by madmaxoft** [comment]
Ah, it is the Lua callback rewrite, a `nil` is not a valid callback, so `GetStackValues()` corerctly reports that some of the values couldn't be read. This needs a bit more thinking. Thanks for the workaround.

**Comment by LogicParrot** [comment]
Related:
https://github.com/cuberite/Core/pull/170
https://github.com/cuberite/cuberite/issues/3305
