### ISSUE TITLE
Some WebAdmin tabs are broken 

### ISSUE THREAD

**Issue by NiLSPACE** [cuberite/Core#249]
After [864e351](https://github.com/cuberite/Core/commit/864e3512c4d38ba6452f89d2ad84e5a71fdc5a30) some webadmin tabs are broken. The commit made URLs partially lower-case while the Javascript/HTML is still using PascalCase. 

I see 3 ways to fix this. We could:

- Change everything back to PascalCase / the original URLs
- Make everything snake-case. This would also require us to look into all the html and javascript code.
- Change Cuberite itself to make the URLs case-insensitive.

I personally prefer the first one. URLs now have mixed casings in it because the name of the plugin itself is also used in the URL.

**Comment by mathiascode** [comment]
Thanks for the bug report. I wasn't aware some URLs were hardcoded.

I used the same URL format as the Gallery plugin, since @madmaxoft made that change (https://github.com/cuberite/gallery/commit/146f8e35b8f2d3ec414cbb07bf772b5dd2077984) and also introduced `cWebAdmin:AddWebTab` in the past.
